### ISSUE TITLE
delay() on 20 & 24MHz is wrong

### ISSUE THREAD

**Issue by Jackjan4** [MCUdude/MCUdude_corefiles#13]
This is just for the books. It all started [here](https://github.com/MCUdude/MiniCore/issues/78).

**Comment by Jackjan4** [comment]
Here is my pull request for a first fix for 20MHz that provides 99.5% accuracy. #14 
Maybe we can go even better, but for now this is definitly a good improvement.

**Comment by MCUdude** [comment]
Almost there 😉 You still have a little bit left inside the micros() function. Line 88-132

**Comment by MCUdude** [comment]
If you want to start working on a 24 MHz fix I can so some testing for you. I just found a 24.000 MHz crystal in my electronics junk bin!

**Comment by Jackjan4** [comment]
> 
> 
> If you want to start working on a 24 MHz fix I can so some testing for you. I just found a 24.000 MHz crystal in my electronics junk bin!

Thank you for the offer :) But I already ordered some yesterday because I need them anyway for a project :)
