### ISSUE TITLE
Accurate delayMicroseconds for 14.7456 MHz, 11.0592 MHz, 7.3728 MHz, 3.6864 MHz and 1.8432 MHz

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MCUdude_corefiles#18]
I've just [pushed a commit](https://github.com/MCUdude/MCUdude_corefiles/commit/87171c2c6ecd8bd7d0a16abca7986c21a316e390) where I've added accurate micros for these clock frequencies. However, I'm not _that_ good with cycle accurate timing that I feel qualified for this job.

I'm sorry to bother you again @Jackjan4, but you did such a wonderful job with the other clock frequencies a few months 🥇 I fully understand if you don't have time or simply don't want to spend time on this, but if you want to contribute I'll promise to do all the testing with my signal generator as clock source.

If this turns out to be a success I'm sure ATTinyCore could benefit from this code as well, since it's missing accurate **delayMicroseconds** for these frequencies too.

Thanks!

**Comment by Jackjan4** [comment]
I'm always happy when I can help. Just give me some days and I can provide solutions for them. I will probably start with the smallest ones first. :) 👍

**Comment by MCUdude** [comment]
Cool, thank you! I think it's smart to start with the lower frequencies first, yes. These "weird" frequencies all add up to each other:

3.6864 MHz = 1.8432 MHz * 2
7.3728 MHz = 3.6864 MHz * 2
11.0592 MHz = 7.3728 MHz + 3.6864 MHz
14.7456 MHz = 7.3728 MHz

**Comment by MCUdude** [comment]
I should probably tell you that tomorrow I'm heading to China for a week (business trip). This basically means I'm not able to respond to your messages while I'm there.

However, my wife at work this evening, so I got plenty of time tonight 😄

**Comment by MCUdude** [comment]
Any news @Jackjan4? 🙂

**Comment by Jackjan4** [comment]
Hi,

i'm very sorry for this super late response, but University really kicked in I was unable to really do some other stuff beside from that. However, i'm back at it again and hope that my help is still needed. :)
I already prepared some code that can be tested out. So if this issue is still up-to-date I will create a PR!

**Comment by MCUdude** [comment]
No worries! I'm just happy you're willing to contribute. It is voluntary work after all 🙂.

It would be great if you prepared some code for the different clock frequencies. Then I can test them all and provide you the results. Just bear in mind that the "automatic code inspection" (Travis CI) doesn't accept tabs and trailing white spaces after a code line.

**Comment by MCUdude** [comment]
See commit e11435e
