### ISSUE TITLE
Travis fails

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MCUdude_corefiles#20]
@per1234 would you look into this? It seems like its having problems downloading all the different IDE versions.

**Comment by per1234** [comment]
I think it was just a momentary glitch unrelated to the contents of this repository or its Travis CI configuration. Likely there was a momentary network outage either on Travis CI's end or Arduino's and the download of one of the IDE files failed.

If you click the "Restart build" button on https://travis-ci.org/MCUdude/MCUdude_corefiles/builds/545465257 that build should pass this time (it did for me at least).

**Comment by MCUdude** [comment]
That's true, it was just a glitch. Thanks!
