### ISSUE TITLE
Radical suggestion

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MCUdude_corefiles#21]
Currently you have minicore, mightycore, majorcore and megacore...
Each of these has one entry in the tools -> board menu for each part... 

I have a bold and radical suggestion (and certainly one that I would expect you to think long and hard about...

Why not combine them all into one core? It would cover all the classic megaAVR parts. Replace the board menu entries with the families, ie
"ATmega 328/168/88/48"
"ATmega 1284/644/324/32/16"
and then a tools submenu to choose which part after selecting that board.... 

That way, people would have to install fewer cores, and there would be less clutter in the tools menu, and you'd only need to maintain one package. 

I have another idea for reducing clutter in menus from our board packages too... need to to a bit more research first though..... (and yes, I AM getting sick of the way that my menus are now several screens long, what gave it away?)

But yeah, it's something to think about...

**Comment by MCUdude** [comment]
Before we start discussing, I'll encourage you to install the latest nightly build. It has a different tools menu, and IMO is much easier to navigate in. I'm sure you'll like it!  
  
It is a good idea, and I have considered it. The main issue is really that the boards.txt file doesn't support any logic, other than the binary hacks we've been using to trick Avrdude. For instance, ATmega32 and ATmega324 have vastly different fuse settings, so it would be impossible to select between these in a variants submenu. This definitely complicates things.

**Comment by SpenceKonde** [comment]
Yeah, sure - putting those as separate board entries would make sense if they're that different. My point is just to squeeze down the number of board entries. 

I'll check out that version of the IDE - but unfortunately the recent versions of the IDE seem to have gotten rid of the checkbox to disable "Aggressively cache core" which makes them totally useless for core development....

**Comment by SpenceKonde** [comment]
Huh! That is really cool that they did it like that! I like it! Certainly reduces the need for something like this from that standpoint

**Comment by MCUdude** [comment]
It's not they, it's matthijskooijman, a guy that has nothing to do with Arduino IIRC. However, it seems like you will have to add dedicated programmers for each core now. But that's totally fine IMO.

**Comment by SpenceKonde** [comment]
I *REALLY* hope they leave it like this! The way that the programmers supplied by each core proliferate, and how incompatible programmers are always shown is a huge boon. The ugly errors that you got when using an inappropriate programmer for the architecture were unpleasant too. 

We will need to be on watch for complaints about it in arduino github and step in in defense of this change.... I know some people are sure to bitch about it. 

This obliviates the other thing I was going to suggest (which I'm not sure could be done), namely adding in a package that only contained programmers and having our cores all pull in that package if it wasn't installed, soas not to duplicate programmer entries.... This solution is WAY the hell better! Means we will need to gather lists of all the useful programmers we should have on our cores - but that's not hard at all...

I think I've seen that guy making useful contributions elsewhere too, actually!
