### ISSUE TITLE
Atmega8a-PU (DIP-28) @ internal 8Mhz  issue

### ISSUE THREAD

**Issue by chsumanbabu** [MCUdude/MCUdude_corefiles#22]
![New Bitmap Image](https://user-images.githubusercontent.com/9160426/90308933-7dfe4a80-df01-11ea-8356-fdeae742427e.jpg)

I am working on a project with Atemga8a-pu  (DIP-28) controller.
I want to use all the IO pins including Tx and RX pins and without external crystal oscillator,
so I decided to program the controller using ISP method and with internal @ 8Mhz. 
The test program is working fine with 16Mhz external crystal and not working with 8 Mhz internal.

please suggest...

**Comment by MCUdude** [comment]
What isn't working? I don't see any errors.

**Comment by chsumanbabu** [comment]
Problem solved now working fine,
wiring connections problem

**Comment by chsumanbabu** [comment]
unable to burn the bootloader on DIP @ 8Mhz internal
Verbose output attached
[TQFP_8Mhz_bootloader.txt](https://github.com/MCUdude/MCUdude_corefiles/files/5078894/TQFP_8Mhz_bootloader.txt)
[DIP_16Mhz_bootlaoder.txt](https://github.com/MCUdude/MCUdude_corefiles/files/5078895/DIP_16Mhz_bootlaoder.txt)
[DIP_8Mhz_bootloader.txt](https://github.com/MCUdude/MCUdude_corefiles/files/5078896/DIP_8Mhz_bootloader.txt)

**Comment by MCUdude** [comment]
You'll have to ask about this on a forum. This is a typical hardware issue.
