### ISSUE TITLE
Support for ATmega48PB/88PB/168PB/328PB should be considered

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MCUdude_corefiles#4]
it's [announced](https://github.com/arduino/toolchain-avr/issues/36) that the ATmega328PB will be supported in the next "Arduino toolchain". Support for the new *PB series should be considered, with all the bells and whistles they have!

**Comment by MCUdude** [comment]
It seems like support for ATmega48PB/88PB/168PB is all there in the latest IDE (1.8.5). I should probably look into this pretty soon. First I need to design a proper development board so I easily can switch between different microcontrollers in TQFP packages.

I think I'll wait with 328PB support until it's actually supported by the IDE. Do you know when we can expect native 328PB support in the toolchain that ships with Arduino IDE @per1234 ?

**Comment by per1234** [comment]
My suspicion is that it will come out with Arduino IDE 1.9.0 but I have no information to base that on. There are some major changes in 1.9.0 so I guess might as well throw in a new toolchain along with it for kicks, right? There are some [outstanding blocking issues](https://github.com/arduino/arduino-preprocessor/issues) with the new arduino-preprocessor tool that will definitely need to be resolved before Arduino IDE 1.9.0 can be released and I haven't seen any activity on those. Actually the Arduino Web Editor has been using arduino-preprocessor for some time now and there haven't been that many issues reported so it shouldn't be too traumatic.

**Comment by MCUdude** [comment]
Good! Meanwhile I'll prepare MCUdude_corefiles to handle all new *8PB variants.

**Comment by MCUdude** [comment]
It seems like the v1.6.200 boards manager package contains an updated toolchain (avr-gcc 5.4.0, ATmega328pb support), so It's fairly easy for users to make the 328PB work with their already installed IDE. At least thats what Watterott's 328PB repo does.

I have a small dev board with a 328PB. Will do some more testing in the following days. I'm open to pull requests if you find any bugs or things that can be improved.

**Comment by MCUdude** [comment]
I think there might be a bug in the v1.6.200 toolchain. I tried to run the analogReadSerial example, but the microcontroller just wrote jibberish inn the serial monitor. I tried with MiniCore 328p and 328pb, MegaCore with 64A and "regular" Arduino UNO.

It happends when printing av number using print() or println().

Problem solved when downgrading to v1.6.20. Any idea what might cause this @per1234?

**Comment by MCUdude** [comment]
For recerence: [https://github.com/arduino/Arduino/issues/6899](https://github.com/arduino/Arduino/issues/6899)

**Comment by MCUdude** [comment]
I'm finishing off designing a development for the new *PB series. It's designed to use TQFP32/QFN32 packages, and should work with all variants. However, it's chinese new year right now, so it's going to take a while before I receive the finished boards.

I'm open for feedback if you believe something should be added/changed on the board.

@per1234 give me a wink if you need a board + some spare modules for testing 👍 

![image](https://user-images.githubusercontent.com/3238730/36282735-6afba35c-12a2-11e8-85ef-2288c9836e97.png)
![image](https://user-images.githubusercontent.com/3238730/36282755-7fa05046-12a2-11e8-9b98-d09199c3509e.png)
![image](https://user-images.githubusercontent.com/3238730/36282831-bd6f2762-12a2-11e8-998f-7716a901ac54.png)
![image](https://user-images.githubusercontent.com/3238730/36282880-e46833fe-12a2-11e8-813c-4e48d4d58d0f.png)

**Comment by per1234** [comment]
Looks great! I don't see the RSTEN header like you have on the MightyCore board. I've heard that people have found they need to cut the RESET-EN jumper on the Arduino boards before debugWire will work on them. Maybe because the auto-reset capacitor interferes with the communication on the reset pin? If that's the case with your board, that header would be a very useful feature to anyone with a debugger. Of course not many Arduino users do have one but maybe that will become a more common tool in the future. There has been official talk of adding on-chip debugging support to the Arduino IDE in the past but no obvious signs of progress in that direction so far.

Nice work on catching the problem with the new AVR toolchain! I'm glad to see Arduino is willing to make the effort to add support for these new chips even though they will likely never be used on an Arduino product.

**Comment by MCUdude** [comment]
> I don't see the RSTEN header like you have on the MightyCore board

If you take a look at the MegaCore dev board I sent you, you'll see that you can disable auto reset by removing R7. I added a 0R resistor to this (MiniCore dev board) as well, but I haven't added instruction on the silk screen yet. I think this looks nicer, require less work for me to assemble and is doable for a person with a soldering iron.

BTW any chances to add Travis CI to the PB_support branch? I'm quite confident that the branch soon is ready to be merged into the master branch. We have new targets and new libraries. Just note that Wire1 and SPI1 doesn't compile on any other micro than ATmega328PB.

> Nice work on catching the problem with the new AVR toolchain! I'm glad to see Arduino is willing to make the effort to add support for these new chips even though they will likely never be used on an Arduino product.

I was actually trying to figure out why PWM digital pin 2 on the 328PB didn't work as it should (turns out there's a [silicon bug in there](https://github.com/watterott/ATmega328PB-Testing/issues/29)). I tried to print the value the PWM pin should output, but the output was just gibberish. I hooked the TX pin on the 328PB to my o'scope, and decoded the output. turns out that **Serial.println** actually prints a proper CR+LF as its last two characters. It's the actual "print part" that doesn't work properly. Let's hope the Arduino developers is able to figure out what's happening!

**Comment by per1234** [comment]
>any chances to add Travis CI to the PB_support branch?

Sure thing. I will submit a PR for the Travis CI tests of the PB boards soon.

>(turns out there's a silicon bug in there). I tried to print the value the PWM pin should output, but the output was just gibberish.

Bugs on top of bugs!

>Let's hope the Arduino developers is able to figure out what's happening!

Supposedly the fix has already been made:
https://github.com/arduino/toolchain-avr/commit/bccf2d0fff3974b787adbdc747cb6ca123d0e12b

I'm not sure whether they've updated the Arduino AVR Boards 1.6.200 Boards Manager package yet though.

**Comment by per1234** [comment]
I don't know whether you already received the notification. The test version Arduino AVR Boards 1.6.205 [has been released](https://github.com/arduino/toolchain-avr/issues/48#issuecomment-366187110), which has the fix to the macOS bug you encountered.

**Comment by MCUdude** [comment]
Just tried the 1.6.205 release. There's som serious issues with the OS X build.. Seems like the 328PB hardware files doesn't get defined.

**Comment by MCUdude** [comment]
I think it's time to close this. ATmega*8PB support is implemented and fairly tested. There will be bugs, but let's squash them when they show up instead 😉
