### ISSUE TITLE
Update CI script?

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MCUdude_corefiles#6]
Maybe we should consider updating the Travis CI script? Right now the current build is failing (caused by a missing directory it seems), and testing for MiniCore is not implemented.

**Comment by per1234** [comment]
I should have the breakage fixed. The build is in progress here:
https://travis-ci.org/per1234/MCUdude_corefiles/builds/328953180
I'll submit a PR as soon as that's verified.

I'll submit a separate PR adding MiniCore testing after that.
